apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: api-example-com-rt
  namespace: gloo-mesh-gateways
spec:
  hosts:
  - api.example.com
  virtualGateways:
  - name: istio-ingressgateway
    namespace: gloo-mesh-gateways
  http:
  - name: httpbin
    labels:
      usagePlans: dev-portal
      route: httpbin
    matchers:
    - uri:
        prefix: /httpbin/
    forwardTo:
      pathRewrite: /
      destinations:
      - kind: VIRTUAL_DESTINATION
        ref:
          name: httpbin-vd
          namespace: httpbin
          cluster: gg-demo-single
        port:
          number: 8000